#!/bin/sh

# SPDX-License-Identifier: BSD-2-Clause

set -e

start_fork() {
	../fork "$@" >log &
	echo $!
}

run() {
	program=$1
	shift
	if [ -n "$program" ] && [ -x "../$program" ]; then
		case "$program" in
			fork)
				PID=$(start_fork -D)
				sleep 1
				kill -INT "$PID"
				sleep 1
				kill "$PID" 2>/dev/null || :
				;;
		esac
	fi
}

run fork -D
grep "DEBUG: SO_LINGER not enabled 0" log && exit 1
run fork -D --linger=-1
grep "DEBUG: SO_LINGER not enabled -1" log
rm -f log out err
